# Generated by Django 5.2.7 on 2025-11-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit/Debit Card"),
                    ("paypal", "PayPal"),
                    ("upi", "UPI"),
                    ("cod", "Cash on Delivery"),
                ],
                default="credit_card",
                max_length=20,
            ),
        ),
    ]
